# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://{{server_host}}:{{server_port}}/

> {% client.test("Is completed", function() {
  client.assert(response.status === 200, "Response status is not 200");
});%}

###

GET http://{{server_host}}:{{server_port}}/build/1

> {% client.test("Is completed", function() {
  client.assert(response.status === 200, "Response status is not 200");
});%}

###

POST http://{{server_host}}:{{server_port}}/notify_build_result
Content-Type: application/json

{
  "id": 1,
  "result": 0,
  "stdout": "",
  "stderr": ""
}

> {% client.test("Is completed", function() {
  client.assert(response.status === 200, "Response status is not 200");
});%}

###

POST http://{{server_host}}:{{server_port}}/notify_agent
Content-Type: application/json

{
  "port": 3000,
  "stdout": "localhost",
  "protocol": "http"
}

> {% client.test("Is completed", function() {
  client.assert(response.status === 200, "Response status is not 200");
});%}

###

POST http://{{agent_host}}:{{agent_port}}/build
Content-Type: application/json

{
  "port": 3000,
  "stdout": "localhost",
  "protocol": "http"
}

> {% client.test("Is completed", function() {
  client.assert(response.status === 200, "Response status is not 200");
});%}

###